### ISSUE TITLE
Team settings gets a 404 error

### ISSUE THREAD

**Issue by popenke** [morkro/papyrus#6]
In this screen when I click on **Team settings** button the app gets a 404 error. 

![team settings](https://cloud.githubusercontent.com/assets/395142/22357072/f1fe1dd6-e41c-11e6-9da0-84376e201335.png)

I believe that Dropbox team are still building this page, but would be nice to disable the access to this button in Papyrus, only by now.

In Firefox, `display: none` seems to solve the problem. But I don't know how Papyrus can apply this dynamically.

**Comment by popenke** [comment]
I think I've solved it, but in a very ugly way, haha.

```css
/* Remove team settings button to avoid 404 error */
#hp-page-pad-list > div.hp-list-page-header.hp-header.hp-list-page-controls > div > div.hp-list-page-controls-inner2 > div > div.hp-sidebar-account-dropdown.hp-account-with-settings.hp-dropdown.hp-dropdown-open > div.hp-dropdown-menu-wrapper > div > ul > li:nth-child(6) > a {
	display: none;
}
```

I've created a pull request #7.
